### ISSUE TITLE
no such controller : Plack (App/AutoCRUD.pm:173)

### ISSUE THREAD

**Issue by Chaz6** [damil/App-AutoCRUD#4]
I am trying to run App::AutoCRUD as FastCGI with the following invocation:-
```
plackup -s FCGI --listen /tmp/app.sock crud.psgi
```

Contents of crud.psgi:-
```
#!/usr/bin/env perl

use App::AutoCRUD;
use YAML qw/LoadFile/;
my $config = LoadFile "/var/www/vhosts/example.com/config.yaml";
my $crud   = App::AutoCRUD->new(config => $config);
my $app    = $crud->to_app;
```

Contents of config.yaml:-
```
app:
  name: Test AutoCRUD

datasources :
  Source1 :
    dbh:
      connect:
          # arguments that will be passed to DBI->connect(...)
          # for example :
        - dbi:SQLite:dbname=/var/www/vhosts/example.com/example.com.db
        - "" # user
        - "" # password
        - RaiseError    : 1
          sqlite_unicode: 1
```

When accessing the page from a browser, it outputs the following:-
```
500 Server Error

no such controller : Plack at /home/chaz/perl5/lib/perl5/App/AutoCRUD.pm line 173.
```

**Comment by damil** [comment]
Hi Chris,

I'm no expert on FCGI, never used it -- so I don't know if your problem 
has to do with your FCGI config or with the app.

Maybe you could try plackup without the -s option to see if it works 
with the standalone builtin server.

Also, maybe there is a problem with the URL you try to access. The error 
message seems to indicate that your URL finishes with /Plack; so the 
application tries to find a controller (within CRUD) of name "Plack" and 
doesn't find it. Try to access the root location where you mounted the 
CRUD app.

Good luck, Laurent


Le 11.08.2019 à 21:00, Chris Hills a écrit :

**Comment by Chaz6** [comment]
Thhnks for your help! I had forwarded from a path with /plack/ and it was not re-written properly. It was coincidence that I picked the same name making me think perhaps it was a big.
