### ISSUE TITLE
The 'Perl source code' link does not work

### ISSUE THREAD

**Issue by chenri2006** [damil/App-AutoCRUD#6]
500 Server Error

no Plain view at /u01/ops/perl-5.36.0/lib/site_perl/5.36.0/App/AutoCRUD/Controller/Schema.pm line 47.

**Comment by damil** [comment]
Hi,
There seems to be an installation problem. Are all AutoCRud subclasses installed in a directory seen by your PERL5LIB ?
I double checked, the "Plain" view is in the distribution and is mentioned in the MANIFEST (https://metacpan.org/release/DAMI/App-AutoCRUD-0.14/source/lib/App/AutoCRUD/View/Plain.pm)

**Comment by damil** [comment]
Without any news, so I close this issue
